"""Autogenerated using entrypoint generator."""

entrypoint = {
    "@type": "EntryPoint",
    "cots": "api/cots/",
    "@context": "http://hydrus.com/api/contexts/EntryPoint.jsonld",
    "@id": "http://hydrus.com/api/"
}
