"""Autogenerated using entrypoint generator."""

entrypoint = {
    "spacecraft_thermal_activedevice": "api/Spacecraft_Thermal_ActiveDevice/",
    "spacecraft_thermal": "api/Spacecraft_Thermal/",
    "spacecraft_cdh": "api/Spacecraft_CDH/",
    "spacecraft_structure": "api/Spacecraft_Structure/",
    "spacecraft_backuppower": "api/Spacecraft_BackupPower/",
    "spacecraft_communication": "api/Spacecraft_Communication/",
    "spacecraft_primarypower.": "api/Spacecraft_PrimaryPower./",
    "spacecraft_aodcs_passivedevice": "api/Spacecraft_AODCS_PassiveDevice/",
    "spacecraft_aodcs": "api/Spacecraft_AODCS/",
    "spacecraft_propulsion.": "api/Spacecraft_Propulsion./",
    "cubicmillimeters": "api/cubicMillimeters/",
    "spacecraft_detector": "api/Spacecraft_Detector/",
    "spacecraft_aodcs_active": "api/Spacecraft_AODCS_Active/",
    "spacecraft_thermal_passivedevice": "api/Spacecraft_Thermal_PassiveDevice/",
    "@context": "http://hydrus.com/api/contexts/EntryPoint.jsonld",
    "@id": "http://hydrus.com/api/",
    "@type": "EntryPoint"
}
