"""Autogenerated using hydrus.hydraspec.entrypoint_generator."""

entrypoint = {   '@context': '/api/contexts/EntryPoint.jsonld',
    '@id': '/api',
    '@type': 'EntryPoint',
    'spacecraft_aodcs': '/api/Spacecraft_AODCS',
    'spacecraft_aodcs_active': '/api/Spacecraft_AODCS_Active',
    'spacecraft_aodcs_passivedevice': '/api/Spacecraft_AODCS_PassiveDevice',
    'spacecraft_backuppower': '/api/Spacecraft_BackupPower',
    'spacecraft_cdh': '/api/Spacecraft_CDH',
    'spacecraft_communication': '/api/Spacecraft_Communication',
    'spacecraft_detector': '/api/Spacecraft_Detector',
    'spacecraft_primarypower': '/api/Spacecraft_PrimaryPower',
    'spacecraft_propulsion': '/api/Spacecraft_Propulsion',
    'spacecraft_structure': '/api/Spacecraft_Structure',
    'spacecraft_thermal': '/api/Spacecraft_Thermal',
    'spacecraft_thermal_activedevice': '/api/Spacecraft_Thermal_ActiveDevice',
    'spacecraft_thermal_passivedevice': '/api/Spacecraft_Thermal_PassiveDevice'}
