"""Parsed classes generated by hydrus.hydraspec.parser.py for subsystem data."""

parsed_classes = [
    {
        "description": "unit of measure for volume",
        "title": "cubicMillimeters",
        "supportedOperation": [
            {
                "returns": "cubicMillimeters",
                "description": "null",
                "statusCodes": [],
                "expects": "cubicMillimeters",
                "label": "Creates a new cubicMillimeters entity",
                "@id": "_:cubicMillimeters_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "cubicMillimeters",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the cubicMillimeters entity wasn't found."
                    }
                ],
                "expects": "cubicMillimeters",
                "label": "Replaces an existing cubicMillimeters entity",
                "@id": "_:cubicMillimeters_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a cubicMillimeters entity",
                "@id": "_:cubicMillimeters_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "cubicMillimeters",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the cubicMillimeters entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a cubicMillimeters entity",
                "@id": "_:cubicMillimeters_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/cubicMillimeters",
        "@type": "hydra:Class"
    },
    {
        "description": "A space detector is a sensor supported by another device that let it collect data, that is deployed into a spacecraft and works outside Earth lower atmosphere",
        "title": "Spacecraft_Detector",
        "supportedOperation": [
            {
                "returns": "Spacecraft_Detector",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_Detector",
                "label": "Creates a new Spacecraft_Detector entity",
                "@id": "_:Spacecraft_Detector_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_Detector",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Detector entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_Detector",
                "label": "Replaces an existing Spacecraft_Detector entity",
                "@id": "_:Spacecraft_Detector_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_Detector entity",
                "@id": "_:Spacecraft_Detector_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_Detector",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Detector entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_Detector entity",
                "@id": "_:Spacecraft_Detector_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:objective",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:isComponentOf",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasVoltage",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_Detector",
        "@type": "hydra:Class"
    },
    {
        "description": "Complex devices-subsystems used for impelling (processes of applying a force which results in translational motion) a spacecraft, in the specific http://umbel.org/umbel/rc/ProjectilePropelling",
        "title": "Spacecraft_Propulsion",
        "supportedOperation": [
            {
                "returns": "Spacecraft_Propulsion",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_Propulsion",
                "label": "Creates a new Spacecraft_Propulsion entity",
                "@id": "_:Spacecraft_Propulsion_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_Propulsion",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Propulsion entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_Propulsion",
                "label": "Replaces an existing Spacecraft_Propulsion entity",
                "@id": "_:Spacecraft_Propulsion_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_Propulsion entity",
                "@id": "_:Spacecraft_Propulsion_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_Propulsion",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Propulsion entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_Propulsion entity",
                "@id": "_:Spacecraft_Propulsion_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "description": "The function and the objective what the device performs or make possible",
                "title": "function",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the subsystem to the kind of the devices it holds.",
                "title": "subSystemType",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the standard platform for which the subsystem has been designed.",
                "title": "isStandard",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:isStandard",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasVolume",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasVolume",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMinAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMinAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMaxAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMaxAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMass",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMass",
                "@type": "SupportedProperty"
            },
            {
                "title": "minWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "maxWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasPower",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasPower",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasSpecificImpulse",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasSpecificImpulse",
                "@type": "SupportedProperty"
            },
            {
                "description": "Amount of money it can be bought for, or an esteem of value.",
                "title": "hasMonetaryValue",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMonetaryValue",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device receive input from another device",
                "title": "hasWireInWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device send output to another device",
                "title": "hasWireOutWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:isSubsystemOf",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:typeOfPropellant",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasSpecificImpulse",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_Propulsion",
        "@type": "hydra:Class"
    },
    {
        "description": "Complex devices-subsystems used for collecting energy.",
        "title": "Spacecraft_PrimaryPower",
        "supportedOperation": [
            {
                "returns": "Spacecraft_PrimaryPower",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_PrimaryPower",
                "label": "Creates a new Spacecraft_PrimaryPower entity",
                "@id": "_:Spacecraft_PrimaryPower_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_PrimaryPower",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_PrimaryPower entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_PrimaryPower",
                "label": "Replaces an existing Spacecraft_PrimaryPower entity",
                "@id": "_:Spacecraft_PrimaryPower_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_PrimaryPower entity",
                "@id": "_:Spacecraft_PrimaryPower_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_PrimaryPower",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_PrimaryPower entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_PrimaryPower entity",
                "@id": "_:Spacecraft_PrimaryPower_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "description": "The function and the objective what the device performs or make possible",
                "title": "function",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the subsystem to the kind of the devices it holds.",
                "title": "subSystemType",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the standard platform for which the subsystem has been designed.",
                "title": "isStandard",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:isStandard",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasVolume",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasVolume",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMinAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMinAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMaxAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMaxAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMass",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMass",
                "@type": "SupportedProperty"
            },
            {
                "title": "minWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "maxWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasPower",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasPower",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasSpecificImpulse",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasSpecificImpulse",
                "@type": "SupportedProperty"
            },
            {
                "description": "Amount of money it can be bought for, or an esteem of value.",
                "title": "hasMonetaryValue",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMonetaryValue",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device receive input from another device",
                "title": "hasWireInWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device send output to another device",
                "title": "hasWireOutWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:isSubsystemOf",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasEfficiency",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasVoltage",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_PrimaryPower",
        "@type": "hydra:Class"
    },
    {
        "description": "Complex devices-subsystems used for storing energy.",
        "title": "Spacecraft_BackupPower",
        "supportedOperation": [
            {
                "returns": "Spacecraft_BackupPower",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_BackupPower",
                "label": "Creates a new Spacecraft_BackupPower entity",
                "@id": "_:Spacecraft_BackupPower_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_BackupPower",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_BackupPower entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_BackupPower",
                "label": "Replaces an existing Spacecraft_BackupPower entity",
                "@id": "_:Spacecraft_BackupPower_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_BackupPower entity",
                "@id": "_:Spacecraft_BackupPower_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_BackupPower",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_BackupPower entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_BackupPower entity",
                "@id": "_:Spacecraft_BackupPower_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "description": "The function and the objective what the device performs or make possible",
                "title": "function",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the subsystem to the kind of the devices it holds.",
                "title": "subSystemType",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the standard platform for which the subsystem has been designed.",
                "title": "isStandard",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:isStandard",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasVolume",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasVolume",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMinAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMinAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMaxAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMaxAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMass",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMass",
                "@type": "SupportedProperty"
            },
            {
                "title": "minWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "maxWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasPower",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasPower",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasSpecificImpulse",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasSpecificImpulse",
                "@type": "SupportedProperty"
            },
            {
                "description": "Amount of money it can be bought for, or an esteem of value.",
                "title": "hasMonetaryValue",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMonetaryValue",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device receive input from another device",
                "title": "hasWireInWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device send output to another device",
                "title": "hasWireOutWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:isSubsystemOf",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_BackupPower",
        "@type": "hydra:Class"
    },
    {
        "description": "Shields, shells or any device insulation from/reflecting radiation exploiting emission and absorption events",
        "title": "Spacecraft_Thermal",
        "supportedOperation": [
            {
                "returns": "Spacecraft_Thermal",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_Thermal",
                "label": "Creates a new Spacecraft_Thermal entity",
                "@id": "_:Spacecraft_Thermal_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_Thermal",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Thermal entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_Thermal",
                "label": "Replaces an existing Spacecraft_Thermal entity",
                "@id": "_:Spacecraft_Thermal_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_Thermal entity",
                "@id": "_:Spacecraft_Thermal_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_Thermal",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Thermal entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_Thermal entity",
                "@id": "_:Spacecraft_Thermal_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "description": "The function and the objective what the device performs or make possible",
                "title": "function",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the subsystem to the kind of the devices it holds.",
                "title": "subSystemType",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the standard platform for which the subsystem has been designed.",
                "title": "isStandard",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:isStandard",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasVolume",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasVolume",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMinAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMinAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMaxAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMaxAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMass",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMass",
                "@type": "SupportedProperty"
            },
            {
                "title": "minWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "maxWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasPower",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasPower",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasSpecificImpulse",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasSpecificImpulse",
                "@type": "SupportedProperty"
            },
            {
                "description": "Amount of money it can be bought for, or an esteem of value.",
                "title": "hasMonetaryValue",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMonetaryValue",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device receive input from another device",
                "title": "hasWireInWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device send output to another device",
                "title": "hasWireOutWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_Thermal",
        "@type": "hydra:Class"
    },
    {
        "description": "They are passive because they mostly transform radiation into heating/cooling ",
        "title": "Spacecraft_Thermal_PassiveDevice",
        "supportedOperation": [
            {
                "returns": "Spacecraft_Thermal_PassiveDevice",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_Thermal_PassiveDevice",
                "label": "Creates a new Spacecraft_Thermal_PassiveDevice entity",
                "@id": "_:Spacecraft_Thermal_PassiveDevice_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_Thermal_PassiveDevice",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Thermal_PassiveDevice entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_Thermal_PassiveDevice",
                "label": "Replaces an existing Spacecraft_Thermal_PassiveDevice entity",
                "@id": "_:Spacecraft_Thermal_PassiveDevice_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_Thermal_PassiveDevice entity",
                "@id": "_:Spacecraft_Thermal_PassiveDevice_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_Thermal_PassiveDevice",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Thermal_PassiveDevice entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_Thermal_PassiveDevice entity",
                "@id": "_:Spacecraft_Thermal_PassiveDevice_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_Thermal_PassiveDevice",
        "@type": "hydra:Class"
    },
    {
        "description": "Complex devices-subsystems used to protect sensors or electronic devices from over/under-heating, like refrigeration absorption.",
        "title": "Spacecraft_Thermal_ActiveDevice",
        "supportedOperation": [
            {
                "returns": "Spacecraft_Thermal_ActiveDevice",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_Thermal_ActiveDevice",
                "label": "Creates a new Spacecraft_Thermal_ActiveDevice entity",
                "@id": "_:Spacecraft_Thermal_ActiveDevice_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_Thermal_ActiveDevice",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Thermal_ActiveDevice entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_Thermal_ActiveDevice",
                "label": "Replaces an existing Spacecraft_Thermal_ActiveDevice entity",
                "@id": "_:Spacecraft_Thermal_ActiveDevice_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_Thermal_ActiveDevice entity",
                "@id": "_:Spacecraft_Thermal_ActiveDevice_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_Thermal_ActiveDevice",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Thermal_ActiveDevice entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_Thermal_ActiveDevice entity",
                "@id": "_:Spacecraft_Thermal_ActiveDevice_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_Thermal_ActiveDevice",
        "@type": "hydra:Class"
    },
    {
        "description": "It's the skeleton and framework of the spacecraft.",
        "title": "Spacecraft_Structure",
        "supportedOperation": [
            {
                "returns": "Spacecraft_Structure",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_Structure",
                "label": "Creates a new Spacecraft_Structure entity",
                "@id": "_:Spacecraft_Structure_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_Structure",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Structure entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_Structure",
                "label": "Replaces an existing Spacecraft_Structure entity",
                "@id": "_:Spacecraft_Structure_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_Structure entity",
                "@id": "_:Spacecraft_Structure_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_Structure",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Structure entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_Structure entity",
                "@id": "_:Spacecraft_Structure_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "description": "The function and the objective what the device performs or make possible",
                "title": "function",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the subsystem to the kind of the devices it holds.",
                "title": "subSystemType",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the standard platform for which the subsystem has been designed.",
                "title": "isStandard",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:isStandard",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasVolume",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasVolume",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMinAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMinAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMaxAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMaxAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMass",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMass",
                "@type": "SupportedProperty"
            },
            {
                "title": "minWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "maxWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasPower",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasPower",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasSpecificImpulse",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasSpecificImpulse",
                "@type": "SupportedProperty"
            },
            {
                "description": "Amount of money it can be bought for, or an esteem of value.",
                "title": "hasMonetaryValue",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMonetaryValue",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device receive input from another device",
                "title": "hasWireInWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device send output to another device",
                "title": "hasWireOutWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:isSubsystemOf",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:standsMaxTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_Structure",
        "@type": "hydra:Class"
    },
    {
        "description": "The DH system shall: Enable HK and science data flow \\u2013 Housekeeping data (Temperatures, Pressures, Voltages, Currents, Status,...) \\u2013 Attitude data \\u2013 Payload data (e.g., Science data) - Receive and distribute commands - Perform TM and TC protocols - Distribute timing signals - Synchronization of data \\u2013 Time stamping of data - Provide data storage - Execute commands and schedules - Control subsystems and payloads - Monitor spacecraft health - Make autonomous decisions - Perform data compression.",
        "title": "Spacecraft_CDH",
        "supportedOperation": [
            {
                "returns": "Spacecraft_CDH",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_CDH",
                "label": "Creates a new Spacecraft_CDH entity",
                "@id": "_:Spacecraft_CDH_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_CDH",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_CDH entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_CDH",
                "label": "Replaces an existing Spacecraft_CDH entity",
                "@id": "_:Spacecraft_CDH_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_CDH entity",
                "@id": "_:Spacecraft_CDH_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_CDH",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_CDH entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_CDH entity",
                "@id": "_:Spacecraft_CDH_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "description": "The function and the objective what the device performs or make possible",
                "title": "function",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the subsystem to the kind of the devices it holds.",
                "title": "subSystemType",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the standard platform for which the subsystem has been designed.",
                "title": "isStandard",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:isStandard",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasVolume",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasVolume",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMinAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMinAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMaxAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMaxAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMass",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMass",
                "@type": "SupportedProperty"
            },
            {
                "title": "minWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "maxWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasPower",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasPower",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasSpecificImpulse",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasSpecificImpulse",
                "@type": "SupportedProperty"
            },
            {
                "description": "Amount of money it can be bought for, or an esteem of value.",
                "title": "hasMonetaryValue",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMonetaryValue",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device receive input from another device",
                "title": "hasWireInWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device send output to another device",
                "title": "hasWireOutWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:isSubsystemOf",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasVoltage",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasMaxClock",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasMinClock",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasDataStorage",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasDataStorageExternal",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasRAM",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasMinTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasMaxTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_CDH",
        "@type": "hydra:Class"
    },
    {
        "description": "Complex devices-subsystems used for transmitting/receiving radio waves.",
        "title": "Spacecraft_Communication",
        "supportedOperation": [
            {
                "returns": "Spacecraft_Communication",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_Communication",
                "label": "Creates a new Spacecraft_Communication entity",
                "@id": "_:Spacecraft_Communication_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_Communication",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Communication entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_Communication",
                "label": "Replaces an existing Spacecraft_Communication entity",
                "@id": "_:Spacecraft_Communication_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_Communication entity",
                "@id": "_:Spacecraft_Communication_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_Communication",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_Communication entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_Communication entity",
                "@id": "_:Spacecraft_Communication_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "description": "The function and the objective what the device performs or make possible",
                "title": "function",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the subsystem to the kind of the devices it holds.",
                "title": "subSystemType",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the standard platform for which the subsystem has been designed.",
                "title": "isStandard",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:isStandard",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasVolume",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasVolume",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMinAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMinAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMaxAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMaxAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMass",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMass",
                "@type": "SupportedProperty"
            },
            {
                "title": "minWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "maxWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasPower",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasPower",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasSpecificImpulse",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasSpecificImpulse",
                "@type": "SupportedProperty"
            },
            {
                "description": "Amount of money it can be bought for, or an esteem of value.",
                "title": "hasMonetaryValue",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMonetaryValue",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device receive input from another device",
                "title": "hasWireInWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device send output to another device",
                "title": "hasWireOutWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:isSubsystemOf",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasMinTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasMaxTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_Communication",
        "@type": "hydra:Class"
    },
    {
        "description": "Complex devices-subsystems used to set the direction and the position of the spacecraft, it controls flight dynamics.",
        "title": "Spacecraft_AODCS",
        "supportedOperation": [
            {
                "returns": "Spacecraft_AODCS",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_AODCS",
                "label": "Creates a new Spacecraft_AODCS entity",
                "@id": "_:Spacecraft_AODCS_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_AODCS",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_AODCS entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_AODCS",
                "label": "Replaces an existing Spacecraft_AODCS entity",
                "@id": "_:Spacecraft_AODCS_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_AODCS entity",
                "@id": "_:Spacecraft_AODCS_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_AODCS",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_AODCS entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_AODCS entity",
                "@id": "_:Spacecraft_AODCS_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "description": "The function and the objective what the device performs or make possible",
                "title": "function",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the subsystem to the kind of the devices it holds.",
                "title": "subSystemType",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty"
            },
            {
                "description": "A property that references the standard platform for which the subsystem has been designed.",
                "title": "isStandard",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:isStandard",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasVolume",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasVolume",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMinAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMinAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMaxAmpere",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMaxAmpere",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasMass",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMass",
                "@type": "SupportedProperty"
            },
            {
                "title": "minWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "maxWorkingTemperature",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasPower",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasPower",
                "@type": "SupportedProperty"
            },
            {
                "title": "hasSpecificImpulse",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasSpecificImpulse",
                "@type": "SupportedProperty"
            },
            {
                "description": "Amount of money it can be bought for, or an esteem of value.",
                "title": "hasMonetaryValue",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasMonetaryValue",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device receive input from another device",
                "title": "hasWireInWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty"
            },
            {
                "description": "This device send output to another device",
                "title": "hasWireOutWith",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:function",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:standsMaxTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:maxWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:minWorkingTemperature",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:subSystemType",
                "@type": "SupportedProperty",
                "required": "false"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireOutWith",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_AODCS",
        "@type": "hydra:Class"
    },
    {
        "description": "Do NOT use any additional power from the spacecraft generator",
        "title": "Spacecraft_AODCS_Active",
        "supportedOperation": [
            {
                "returns": "Spacecraft_AODCS_ActiveDevice",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_AODCS_ActiveDevice",
                "label": "Creates a new Spacecraft_AODCS_Active entity",
                "@id": "_:Spacecraft_AODCS_Active_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_AODCS_ActiveDevice",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_AODCS_Active entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_AODCS_ActiveDevice",
                "label": "Replaces an existing Spacecraft_AODCS_Active entity",
                "@id": "_:Spacecraft_AODCS_Active_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_AODCS_Active entity",
                "@id": "_:Spacecraft_AODCS_Active_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_AODCS_ActiveDevice",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_AODCS_Active entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_AODCS_Active entity",
                "@id": "_:Spacecraft_AODCS_Active_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_AODCS_ActiveDevice",
        "@type": "hydra:Class"
    },
    {
        "description": "DO use any additional power from the spacecraft generator",
        "title": "Spacecraft_AODCS_PassiveDevice",
        "supportedOperation": [
            {
                "returns": "Spacecraft_AODCS_PassiveDevice",
                "description": "null",
                "statusCodes": [],
                "expects": "Spacecraft_AODCS_PassiveDevice",
                "label": "Creates a new Spacecraft_AODCS_PassiveDevice entity",
                "@id": "_:Spacecraft_AODCS_PassiveDevice_create",
                "@type": "hydras:Operation",
                "method": "POST"
            },
            {
                "returns": "Spacecraft_AODCS_PassiveDevice",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_AODCS_PassiveDevice entity wasn't found."
                    }
                ],
                "expects": "Spacecraft_AODCS_PassiveDevice",
                "label": "Replaces an existing Spacecraft_AODCS_PassiveDevice entity",
                "@id": "_:Spacecraft_AODCS_PassiveDevice_replace",
                "@type": "hydra:Operation",
                "method": "PUT"
            },
            {
                "returns": "null",
                "description": "null",
                "statusCodes": [],
                "expects": "null",
                "label": "Deletes a Spacecraft_AODCS_PassiveDevice entity",
                "@id": "_:Spacecraft_AODCS_PassiveDevice_delete",
                "@type": "hydra:Operation",
                "method": "DELETE"
            },
            {
                "returns": "Spacecraft_AODCS_PassiveDevice",
                "description": "null",
                "statusCodes": [
                    {
                        "code": 404,
                        "description": "If the Spacecraft_AODCS_PassiveDevice entity wasn't found."
                    }
                ],
                "expects": "null",
                "label": "Retrieves a Spacecraft_AODCS_PassiveDevice entity",
                "@id": "_:Spacecraft_AODCS_PassiveDevice_retrieve",
                "@type": "hydra:Operation",
                "method": "GET"
            }
        ],
        "supportedProperty": [
            {
                "title": "manufacturer",
                "required": "false",
                "readonly": "false",
                "writeonly": "false",
                "property": "subsystems:manufacturer",
                "@type": "SupportedProperty"
            },
            {
                "writeonly": "false",
                "readonly": "false",
                "property": "subsystems:hasWireInWith",
                "@type": "SupportedProperty",
                "required": "false"
            }
        ],
        "@id": "http://ontology.projectchronos.eu/subsystems/Spacecraft_AODCS_PassiveDevice",
        "@type": "hydra:Class"
    }
]
