"""Autogenerated using hydrus.hydraspec.entrypoint_context_generator."""

entrypoint_context = {
    "@context": {
        "cots": {
            "@id": "vocab:EntryPoint/Cots",
            "@type": "@id"
        },
        "hydra": "http://www.w3.org/ns/hydra/core#",
        "EntryPoint": "vocab:EntryPoint",
        "vocab": "http://hydrus.com//api/vocab#"
    }
}
